/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "HTSFileArchive.h"
/* Header for class com_ubt_alpha1s_business_HtsHelper */

#ifndef _Included_com_ubt_alpha1s_business_HtsHelper
#define _Included_com_ubt_alpha1s_business_HtsHelper
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_ubt_alpha1s_business_HtsHelper
	 * Method:    writeHts
	 * Signature: (Lcom/ubt/alpha1s/data/model/NewActionInfo;Ljava/lang/String;Lcom/ubt/alpha1s/business/IHtsHelperListener;)V
	 */
	JNIEXPORT void JNICALL Java_com_ubt_alpha1s_business_HtsHelper_writeHts
		(JNIEnv *, jclass, jobject, jstring, jobject);

	/*
	 * Class:     com_ubt_alpha1s_business_HtsHelper
	 * Method:    getNewActionInfoFromHts
	 * Signature: (Lcom/ubt/alpha1s/data/model/NewActionInfo;Ljava/lang/String;Lcom/ubt/alpha1s/business/IHtsHelperListener;)V
	 */
	JNIEXPORT void JNICALL Java_com_ubt_alpha1s_business_HtsHelper_getNewActionInfoFromHts
		(JNIEnv *, jclass, jobject, jstring, jobject);

	char* jstringTostring(JNIEnv* env, jstring jstr);
	void jintArrayTointArray(int* result, JNIEnv* env, jintArray jintarray);
	void FrameDatasToNewActionInfo(JNIEnv* env, jobject j_object, FrameData* datas, int data_size);
	jintArray intsTojintArray(JNIEnv* env, int* array, int size);

#ifdef __cplusplus
}
#endif
#endif
